name: Build and Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    name: Build & Release
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Compile Inno Setup Installer
        uses: robin24/inno-setup-action@v1
        with:
          filepath: installer.iss

      - name: Compress Build Folder with Installer
        run: |
          Compress-Archive -Path "dist\win\planet-builder\*" -DestinationPath "PlanetBuilder.zip" -Force

      - name: Create or update rolling release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Planet Builder - Latest Build"
          files: |
            PlanetBuilder.zip
